# Generated by Django 6.1.1 on 2026-09-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
